from rest_framework import serializers
from ..models.recommendation_models import UserMetrics, BreakRecommendation

class UserMetricsSerializer(serializers.ModelSerializer):
    """Serializer for user metrics that feed into the recommendation engine"""
    class Meta:
        model = UserMetrics
        fields = ['id', 'work_hours_per_week', 'stress_level', 'sleep_quality', 
                 'prefers_travel', 'season_preference', 'break_type_preference',
                 'created_at', 'updated_at']
        read_only_fields = ['id', 'created_at', 'updated_at']
    
    def create(self, validated_data):
        user = self.context['request'].user
        # Check if user already has metrics
        try:
            metrics = UserMetrics.objects.get(user=user)
            # Update existing metrics
            for attr, value in validated_data.items():
                setattr(metrics, attr, value)
            metrics.save()
            return metrics
        except UserMetrics.DoesNotExist:
            # Create new metrics
            return UserMetrics.objects.create(user=user, **validated_data)


class BreakRecommendationSerializer(serializers.ModelSerializer):
    """Serializer for break recommendations generated by the ML engine"""
    class Meta:
        model = BreakRecommendation
        fields = ['id', 'recommended_start_date', 'recommended_end_date', 
                 'predicted_length_days', 'recommended_season', 'message',
                 'is_viewed', 'is_accepted', 'created_at']
        read_only_fields = ['id', 'recommended_start_date', 'recommended_end_date', 
                           'predicted_length_days', 'recommended_season', 
                           'message', 'created_at']
    
    def update(self, instance, validated_data):
        # Only allow updating is_viewed and is_accepted fields
        if 'is_viewed' in validated_data:
            instance.is_viewed = validated_data['is_viewed']
        if 'is_accepted' in validated_data:
            instance.is_accepted = validated_data['is_accepted']
        instance.save()
        return instance