from django.db import models
from django.conf import settings
import uuid
from django.utils import timezone

class UserMetrics(models.Model):
    """Stores user metrics that feed into the recommendation engine"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='metrics'
    )
    work_hours_per_week = models.PositiveIntegerField(default=40)
    stress_level = models.PositiveIntegerField(default=5, help_text="Scale of 1-10")
    sleep_quality = models.PositiveIntegerField(default=5, help_text="Scale of 1-10")
    prefers_travel = models.BooleanField(default=False)
    
    # Seasonal preferences
    SEASON_CHOICES = [
        ('winter', 'Winter (Jan-Mar)'),
        ('spring', 'Spring (Apr-Jun)'),
        ('summer', 'Summer (Jul-Sep)'),
        ('fall', 'Fall (Oct-Dec)'),
        ('no_preference', 'No Preference'),
    ]
    season_preference = models.CharField(max_length=20, choices=SEASON_CHOICES, default='no_preference')
    
    # Break type preferences
    BREAK_TYPE_CHOICES = [
        ('short_frequent', 'Short, Frequent Breaks'),
        ('long_infrequent', 'Long, Infrequent Breaks'),
        ('mixed', 'Mix of Both'),
    ]
    break_type_preference = models.CharField(max_length=20, choices=BREAK_TYPE_CHOICES, default='mixed')
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.user.email}'s Metrics"


class BreakRecommendation(models.Model):
    """Stores break recommendations generated by the ML engine"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='break_recommendations'
    )
    recommended_start_date = models.DateField()
    recommended_end_date = models.DateField()
    predicted_length_days = models.PositiveIntegerField()
    recommended_season = models.CharField(max_length=20)
    message = models.TextField()
    is_viewed = models.BooleanField(default=False)
    is_accepted = models.BooleanField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.user.email}'s Recommendation ({self.created_at.strftime('%Y-%m-%d')})"